server:
  port: 8876
spring:
  application:
    name: demo-provider
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: ${eureka:http://localhost:1111/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'